### ISSUE TITLE
URL for dataset download

### ISSUE THREAD

**Issue by kdwonn** [addtt/object-centric-library#6]
Hello! Thank you for sharing the great code.

I tried to use your repository but found out that provided remote [URL](https://github.com/addtt/object-centric-library/blob/ea1051e3052fc86cb2b2f329f166ca2416375081/download_data.py#L14) for dataset download is not working.
Can you please check if it works?

Also, can you explain how the provided dataset is different from the [Multi-object-dataset](https://github.com/deepmind/multi_object_datasets) from deepmind?

**Comment by addtt** [comment]
Hi, thanks for reaching out! 

The files are all there, it all works fine if you use the download script as described in point 3 [here](https://github.com/addtt/object-centric-library#setting-up-the-environment). I guess you tried to access it via browser and then it prints "hello world" – that's confusing and I'll take care of it.

Differences from the Deepmind suite:
- We have one more dataset
- We have the style-transfer versions of the datasets, which we use in the paper (and in [this follow-up paper](https://arxiv.org/abs/2204.08479))
- We repackage the datasets in hdf5 to avoid dependency on tensorflow, since the original ones are tf datasets. It's a more common and generic standard. We also add some useful metadata.
